spring:
  datasource:
    url: jdbc:mysql://192.168.88.2/qychat_archive?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: usercenter
    password: 1332@ANCH.com

redis:
  model: standalone
  host: 192.168.88.32
  port: 6379
  password: Pp.51idc.com
  database: 0

qychat:
  sdk:
    path: /home/qychat/sdk