spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/qychat_archive?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: usercenter
    password: admini

redis:
  model: standalone
  host: 127.0.0.1
  port: 6379
  password: admini
  database: 0

qychat:
  sdk:
    path: /home/qychat/sdk