server:
  port: 8001

spring:
  profiles:
    active: local
  application:
    name: qychat-archive
#  resources:
#    static-locations: file:d:/data/

qychat:
  chatdata:
    corpid: wwb55a50126edc83d2
    secret: 1jCvYfSyNF2gYeRT6gxNz9_1RK7GNY8mv6-26JrOjK0
    limit: 1000
    timeout: 30
  customer:
    corpid: ${qychat.chatdata.corpid}
    secret: pEie4lS2rB2KtWKcFfC389BHP7Z_ynWYn1UkjWMvlG4


knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: false
    swaggerModelName: 实体类列表
    enableVersion: true
    enableReloadCacheParameter: true
    enableFilterMultipartApis: false
    enableRequestCache: false
    enableFooter: false
    enableFooterCustom: true
    enableOpenApi: false
    enableGroup: true