server:
  port: 8001

spring:
  profiles:
    active: local
  application:
    name: qychat-archive
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#  resources:
#    static-locations: file:d:/data/

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xh.**.model.**.*
  mapper-locations: classpath:mappers/*Mapper.xml


qychat:
  chatdata:
    corpid: wwb5xxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    limit: 1000
    timeout: 30
  customer:
    corpid: ${qychat.chatdata.corpid}
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: false
    swaggerModelName: 实体类列表
    enableVersion: true
    enableReloadCacheParameter: true
    enableFilterMultipartApis: false
    enableRequestCache: false
    enableFooter: false
    enableFooterCustom: true
    enableOpenApi: false
    enableGroup: true